name: puby
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"
# environment:
#   sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # 图片加载
  extended_image: ^4.1.0
  # 底部tabbar 
  convex_bottom_bar: ^3.0.0
  # 网络请求
  dio: ^4.0.0
  # 状态管理器
  flutter_riverpod: ^0.14.0+3
  # 上下啦刷新控件
  pull_to_refresh: ^1.6.5
  # Dart通用工具库
  # 1、TimelineUtil : 时间轴.(新)
  # 2、TimerUtil : 倒计时，定时任务.(新)
  # 3、MoneyUtil : 精确转换，元转分，分转元，支持格式输出.(新)
  # 4、LogUtil : 简单封装打印日志.(新)
  # 5、DateUtil : 日期转换格式化输出.
  # 6、RegexUtil : 正则验证手机号，身份证，邮箱等等.
  # 7、NumUtil : 保留x位小数, 精确加、减、乘、除, 防止精度丢失.
  # 8、ObjectUtil : 判断对象是否为空(String List Map),判断两个List是否相等.
  common_utils: ^2.0.2
  # 轮播图
  flutter_swiper: ^1.1.6
  # 本地数据存储库
  sp_util: ^2.0.3
  # 解决键盘弹起,挡住输入框的问题
  keyboard_avoider: ^0.1.2
  # 适配屏幕尺寸
  flutter_screenutil: ^4.0.3+1
  # 视频播放器
  better_player: ^0.0.68
  # 弹框
  fluttertoast: ^8.0.7
  # 加载字体和动画
  lottie: ^1.0.1
  # web 
  flutter_webview_plugin: ^0.3.10+2

  transparent_image: ^1.0.0
  # 汉字转拼音
  lpinyin: ^2.0.3

  english_words: ^4.0.0

  # 滚动指定的位置
  scrollable_positioned_list: ^0.1.10
  # 获取手机权限
  #permission_handler: ^8.0.1
  # 打电话 
  #url_launcher: ^6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/caigou.png
    - assets/images/caigou_s.png
    - assets/images/gongzuotai.png
    - assets/images/huanzhegoutong.png
    - assets/images/huanzhegoutong_s.png
    - assets/images/wode_s.png
    - assets/images/wode.png
    - assets/images/xueyuan_s.png
    - assets/images/banben.png
    - assets/images/jiangping.png
    - assets/images/kefu.png
    - assets/images/renzheng.png
    - assets/images/sousuo.png
    - assets/images/shezhi.png
    - assets/images/shoucang.png
    - assets/images/shipin.png
    - assets/images/kaifang.png
    - assets/images/lisichufang.png
    - assets/images/shouyao.png
    - assets/images/xiedingchufang.png
    - assets/images/caigouitem.png
    - assets/images/gongyingshang.png
    - assets/images/liliao.png
    - assets/images/pancun.png
    - assets/images/ruku.png
    - assets/images/shouyin.png
    - assets/images/yaofang.png
    - assets/images/auth_dingwei.png
    - assets/images/auth_yiyuan.png
    - assets/images/auth_zhenliao.png
    - assets/images/yijianfankui.png
    - assets/images/zengjia.png
    - assets/images/zengjiay.png
    - assets/images/shanchu.png
    - assets/images/jian.png
    - assets/images/jia.png
    - assets/images/chenggong.png
    - assets/images/xuanzhong.png
    - assets/images/weixuanzhong.png
    - assets/images/pingtaidingdan.png
    - assets/images/xueyuan.png
    - assets/images/xiaoxi.png
    - assets/images/yiyaoxiang.png
    - assets/images/cangshang.png
    - assets/images/gyingshang.png
    - assets/images/yaocaileixing.png
    - assets/images/yaopinweixuanzhong.png
    - assets/images/yaopinxuanzhong.png
    - assets/images/gouwuche.png
    - assets/images/bianxie.png
    - assets/images/yuan.png
    - assets/json/empty.json
    - assets/json/disconnect.json
    - assets/json/error.json
    - assets/json/loading.json
    - assets/json/loadingYellow.json
    - assets/json/loading2.json
    - assets/json/error2.json
    - assets/json/empty2.json
    - assets/json/empty3.json
    - assets/json/china.json
    - assets/images/animationImage.gif


fonts:
  - family: FZDaLTJ
    fonts:
      - asset: assets/fonts/fzDaLTJ.ttf
  - family: FZFWQingYinTiJWL
    fonts:
      - asset: assets/fonts/fzFWQingYinTiJWL.ttf
  - family: FZFWZhuZiAYuanJWM
    fonts:
      - asset: assets/fonts/fzFWZhuZiAYuanJWM.ttf
  - family: SourceHanSans
    fonts:
      - asset: assets/fonts/sourceHanSansMedium.ttc
  - family: Rzzyt
    fonts:
      - asset: assets/fonts/rzzyt.ttf
  - family: IconFont
    fonts:
       - asset: assets/fonts/iconfont.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
